[echoes_config]
generated_class_name = "Objects"
generated_namespace = "HaruEditor.Desktop.Localization"

[translations]
HaruEditor_Core_Tables_P5R_EncountTable = "ENCOUNT.TBL"
HaruEditor_Core_Tables_P5R_EnemyEncounter = "Enemy Encounter"
HaruEditor_Core_Tables_P5R_EnemyEncountersSegment = "Enemy Encounters"
HaruEditor_Core_Tables_P5R_ForcedParty = "Forced Party"
HaruEditor_Core_Tables_P5R_ForcedPartiesSegment = "Forced Parties"
HaruEditor_Core_Tables_P5R_ChallengeBattle = "Challenge Battle"
HaruEditor_Core_Tables_P5R_ChallengeBattlesSegment = "Challenge Battles"

HaruEditor_Core_Tables_P5R_PlayerTable = "PLAYER.TBL"
HaruEditor_Core_Tables_P5R_PlayerLevelUpThresholdsSegment = "Player LV UP Thresholds"
HaruEditor_Core_Tables_P5R_PlayerLevelUpThreshold = "Player LV UP Threshold"
HaruEditor_Core_Tables_P5R_PlayerHPSPPerLevelsSegment = "Player HP/SP per LV"
HaruEditor_Core_Tables_P5R_PlayerHPSPPerLevels = "Player HP/SP per LV"

HaruEditor_Core_Tables_P5R_UnitTable = "UNIT.TBL"
HaruEditor_Core_Tables_P5R_EnemyUnitStatsSegment = "Enemy Unit Stats"
HaruEditor_Core_Tables_P5R_EnemyUnitStats = "Enemy Unit Stats"
HaruEditor_Core_Tables_P5R_EnemyElementalAffinitiesSegment = "Enemy Elemental Affinites"
HaruEditor_Core_Tables_P5R_PersonaElementalAffinitiesSegment = "Persona Elemental Affinites"
HaruEditor_Core_Tables_P5R_ElementalAffinities = "Elemental Affinities"
HaruEditor_Core_Tables_P5R_UnitVoiceIndexSegment = "Unit Voice Indexes"
HaruEditor_Core_Tables_P5R_UnitVoiceIndex = "Unit Voice Index"
HaruEditor_Core_Tables_P5R_UnitVisualIndexSegment = "Unit Visual Indexes"
HaruEditor_Core_Tables_P5R_UnitVisualIndex = "Unit Visual Index"

HaruEditor_Core_Tables_P5R_PersonaTable = "PERSONA.TBL"
HaruEditor_Core_Tables_P5R_PersonaStatsSegment = "Persona Stats"
HaruEditor_Core_Tables_P5R_PersonaStats = "Persona Stats"
HaruEditor_Core_Tables_P5R_PersonaSkillsAndStatGrowthsSegment = "Persona Skills & Stat Growths"
HaruEditor_Core_Tables_P5R_PersonaSkillsAndStatGrowth = "Persona Skills & Stat Growths"
HaruEditor_Core_Tables_P5R_PersonaLevelUpThresholdsSegment = "Persona LV UP Thresholds"
HaruEditor_Core_Tables_P5R_PersonaLevelUpThresholds = "Persona LV UP Thresholds"
HaruEditor_Core_Tables_P5R_PersonaPartyPersonasSegment = "Party Personas"
HaruEditor_Core_Tables_P5R_PersonaPartyPersonas = "Party Personas"

HaruEditor_Core_Tables_P5R_VisualTable = "VISUAL.TBL"
HaruEditor_Core_Tables_P5R_VisualEnemyVisualVariablesASegment = "Enemy Visual Vars A"
HaruEditor_Core_Tables_P5R_VisualEnemyVisualVariablesA = "Enemy Visual Vars A"
HaruEditor_Core_Tables_P5R_VisualPlayerVisualVariablesASegment = "Player Visual Vars A"
HaruEditor_Core_Tables_P5R_VisualPlayerVisualVariablesA = "Player Visual Vars A"
HaruEditor_Core_Tables_P5R_VisualPersonaVisualVariablesASegment = "Persona Visual Vars A"
HaruEditor_Core_Tables_P5R_VisualPersonaVisualVariablesA = "Persona Visual Vars A"

HaruEditor_Core_Tables_P5R_ItemTable = "ITEM.TBL"
HaruEditor_Core_Tables_P5R_ItemAccessorySegment = "Item Acc."
HaruEditor_Core_Tables_P5R_ItemAccessory = "Accessory"
HaruEditor_Core_Tables_P5R_ItemArmorSegment = "Armors"
HaruEditor_Core_Tables_P5R_ItemArmor = "Armor"
HaruEditor_Core_Tables_P5R_ItemConsumableSegment = "Consumables"
HaruEditor_Core_Tables_P5R_ItemConsumable = "Consumable"
HaruEditor_Core_Tables_P5R_ItemKeyItemSegment = "Key Items"
HaruEditor_Core_Tables_P5R_ItemKeyItem = "Key Item"
HaruEditor_Core_Tables_P5R_ItemMaterialSegment = "Materials"
HaruEditor_Core_Tables_P5R_ItemMaterial = "Material"
HaruEditor_Core_Tables_P5R_ItemMeleeWeaponSegment = "Melee Weapons"
HaruEditor_Core_Tables_P5R_ItemMeleeWeapon = "Melee Weapon"
HaruEditor_Core_Tables_P5R_ItemOutfitSegment = "Outfits"
HaruEditor_Core_Tables_P5R_ItemOutfit = "Outfit"
HaruEditor_Core_Tables_P5R_ItemSkillCardSegment = "Skill Cards"
HaruEditor_Core_Tables_P5R_ItemSkillCard = "Skill Card"
HaruEditor_Core_Tables_P5R_ItemRangedWeaponSegment = "Ranged Weapons"
HaruEditor_Core_Tables_P5R_ItemRangedWeapon = "Ranged Weapon"

HaruEditor_Core_Tables_P5R_SkillTable = "SKILL.TBL"
HaruEditor_Core_Tables_P5R_ActiveSkill = "Active Skill"
HaruEditor_Core_Tables_P5R_ActiveSkillSegment = "Active Skills"
HaruEditor_Core_Tables_P5R_SkillElement = "Skill Element"
HaruEditor_Core_Tables_P5R_SkillElementSegment = "Skill Elements"
HaruEditor_Core_Tables_P5R_Trait = "Trait"
HaruEditor_Core_Tables_P5R_TraitSegment = "Traits"
HaruEditor_Core_Tables_P5R_TechnicalComboMap = "Tech. Combo Map"
HaruEditor_Core_Tables_P5R_TechnicalComboMapSegment = "Tech. Combo Maps"